### ISSUE TITLE
Added import of all Jira comments

### ISSUE THREAD

**Issue by P47K0** [Mozketo/WorkitemImporter#1]
Hi Mozketo,

Thanks for sharing this project, it helped me a lot!
I added the import of Jira issue comments to the Sync class.
Are you interested in that? May I do a pull request?
Next to that I made a correction in the app.config, the app setting 'Jira.Project' was missing.

Kind regards,
Patrick

**Comment by Mozketo** [comment]
I'm glad that the project helped you. Please feel free to send through a PR as that, in turn, may help someone else out. I appreciate your assist :)

**Comment by P47K0** [comment]
I get a 403 when I try to push my Feature branch. Do you need to give me rights first?

**Comment by Mozketo** [comment]
I've never accepted a PR in Github, I thought you could fork the code and
send me a PR. In the meantime, I've made you a collaborator
https://github.com/Mozketo/WorkitemImporter/invitations

Ben

**Comment by Mozketo** [comment]
Does this help?
https://services.github.com/on-demand/github-cli/open-pull-request-github

Ben

**Comment by P47K0** [comment]
No it worked, thanks

**Comment by P47K0** [comment]
Yes I was able to push

**Comment by P47K0** [comment]
It is my first time that I collaborate with a github project. I cloned the master branch and then created a local copy of it. I just pushed the local copy. I think I should have forked it instead indeed.

**Comment by P47K0** [comment]
I was also able to do a pull request without forking.

**Comment by Mozketo** [comment]
Awesome, thank you for your changes. I'll close this issue now. 👍
